apiVersion: k3d.io/v1alpha4 
kind: Simple 
metadata:
  name: k3d
servers: 1
agents: 2
image: rancher/k3s:v1.27.6-k3s1
network: my-custom-net
token: someToken # Token for joining the cluster
volumes: 
  - volume: /k3d-volume:/k3d-volume
ports:
  - port: 3000:3000
  - port: 5000:5000
  - port: 8080:80
options:
  k3d:
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
        - settings.workerConnections=2048
  kubeconfig:
    updateDefaultKubeconfig: true